# Usa a imagem oficial do PostgreSQL como base
FROM postgres:15

# Define variáveis de ambiente para o banco
ENV POSTGRES_USER=dev
ENV POSTGRES_PASSWORD=123456
ENV POSTGRES_DB=bridgenet

# Expõe a porta padrão do PostgreSQL
EXPOSE 5432

# Comando padrão já é iniciado pelo postgres:15, não precisa sobrescrever CMD
