version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: imagem-postgres
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bridgenet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
